import { AccountPremium } from './class/AccountPremium'
import { CompanyAccount } from './class/CompanyAccount'
import { PeopleAccount } from './class/PeopleAccount'

const peopleAccount: PeopleAccount = new PeopleAccount(1, 'Nath', 10)
//console.log(peopleAccount)
console.log(`Nome: ${peopleAccount.getName()}`)
console.log(`Número da conta: ${peopleAccount.getAccountNumber()}`)
peopleAccount.deposit(100)
console.log(`Seu saldo é de R$${peopleAccount.getBalance()}`)
peopleAccount.deposit(100)
console.log(`Seu saldo é de R$${peopleAccount.getBalance()}`)
peopleAccount.withdraw(20)
console.log(`Seu saldo é de R$${peopleAccount.getBalance()}`)
console.log('**************')
const companyAccount: CompanyAccount = new CompanyAccount('DIO', 20)
console.log(`Nome: ${companyAccount.getName()}`)
console.log(`Número da conta: ${companyAccount.getAccountNumber()}`)
companyAccount.getLoan(5000)
console.log(`Seu saldo é de R$${companyAccount.getBalance()}`)
//console.log(companyAccount)
console.log('**************')
const accountPremium: AccountPremium = new AccountPremium('Sebastien', 30)
console.log(`Nome: ${accountPremium.getName()}`)
console.log(`Número da conta: ${accountPremium.getAccountNumber()}`)
accountPremium.deposit(100)
console.log(`Seu saldo é de R$${accountPremium.getBalance()}`)